### PR TITLE
Added CMake build file.

### PR DESCRIPTION
**Pull request by aiusepsi**
First pass at a CMake build definition, hewing fairly close to the Meson build.

Tested on Ubuntu 17.10 and macOS High Sierra 10.13.4.

### CODE REVIEW

**Comment by k0ss** [comment]
On Debian stretch (9.4) I found that I had to add `-msse4.1` to `CFLAGS` and `CXXFLAGS` in `CMakeLists.txt` or else I would get multiple errors such as `/usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:690:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch`.  After adding those lines it builds just fine.  I haven't tested building this library with the non-cmake tools that Valve provided so I don't yet know if those flags need to be added there as well for debian.  Thanks for this PR, as I didn't feel like learning another build toolchain :+1:

**Comment by Laaas** [comment]
What is the motivation behind adding CMake support?

**Comment by nerzhul** [comment]
Integrate in CMake supported software easily instead of rewriting a cmake layer over it ?

**Comment by tycho** [comment]
CMake also has better Windows support from what I can see. I haven't figured out how to get the Meson build working with MSVC because Meson discovers dependencies with pkg-config, which isn't particularly easy to set up on Windows without use of something like MinGW.

**Comment by aiusepsi** [comment]
My main general reasons are that CMake is closer to being a _lingua franca_ than Meson, for example (recent versions of) Visual Studio, Android Studio, CLion, and Qt Creator all have native support for CMake.

If you do happen to have any existing CMake projects, having a CMake build is helpful because you can just add this repo as a submodule, add the subdirectory in your CMakeLists.txt, and it'll pull in the targets ready for you to use, and build them from the source on demand. Which is nice. And if you already know CMake, it's nice to be able to use it rather than another system you have no experience with. But yeah, it is to some degree a matter of opinion.

**Comment by tycho** [comment]
Added some CMake build files that are partially based on yours, with some modifications to make it work for MSVC.

**Pull request closed without merging**
