### PR TITLE
add tests to osx build script

### PR DESCRIPTION
**Pull request by AminSojoudi**
Tests were added as new steps to the OSX workflow.
https://github.com/ValveSoftware/GameNetworkingSockets/issues/178

### CODE REVIEW

**Comment by zpostfacto** [comment]
Thanks!  And it looks like the tests detected a problem with my new TOS-reading code.

**Comment by zpostfacto** [comment]
Thanks!
I am not sure if the test is still broken or not, but either way, it's a real break that needs to be fixed.

**Comment by AminSojoudi** [comment]
My Pleasure,
I have tried the tests on older commits and they passed with success. I believe the test process is fine. However, I'm not sure if the failed test is wrong or something inside the library is broken in recent commits.

**Comment by zpostfacto** [comment]
There are recent commits that are almost certainly the cause.

**Pull request merged**
