### PR TITLE
Support for using libsodium for crypto

### PR DESCRIPTION
**Pull request by aiusepsi**
Added compile-time option for using libsodium for crypto, as well as setup for the CI to build and test it. Main caveat is that AES is only supported in libsodium if the CPU has instructions for it.

Probably could do with some cleanup, especially around formatting; is there a style guide and/or a clang-format file for the house style I've overlooked?

Change to abstract Protobuf ByteSize() / ByteSizeLong() is there because one of the Travis builds broke without changing to ByteSizeLong(), and other builds broke if everything was changed to ByteSizeLong(). An alternative solution would be to ignore the deprecation warning.

### CODE REVIEW

**Comment by fletcherdvalve** [comment]
This looks great!

Could you make one small change before this is pulled in?  Basically it'd be great if the CMakefile / meson files detected invalid configurations and failed with a clear message.  E.g. if you defined multiple crypto providers, it should complain.  Right now it's random based on how the script was written and what the defaults are.  This was not a problem you introduced, but now with, 4 different crypto providers in total (if you count the software 25519 stuff as a provider) and the fact that the logic that determines when the software crypto 25519 is used is relatively complicated, I think we should try to give the makefiles some logic that not only detects errors earlier, but also sort of documents which configurations are possible.

**Comment by tycho** [comment]
One option would be to add an option that could be used like `-DWITH_CRYPTO="sodium"`

If it's explicitly specified at configure time, then raise a fatal error if the library in question is not present or otherwise unusable, and don't fall back to anything else (because the user's request could not be satisfied verbatim).

If it's *not* explicitly specified, probe for all possible crypto library providers, and then choose which one to use in order of priority and availability, like openssl > libsodium > bcrypt > whatever.

**Comment by fletcherdvalve** [comment]
Also, can you give some more details about the protobuf deprecation warning?  Is this some issue with using the latest google protobuf compiler?

**Comment by bgilmore** [comment]
> Also, can you give some more details about the protobuf deprecation warning? Is this some issue with using the latest google protobuf compiler?

Last year Google added a deprecation warning for ByteSize: https://github.com/protocolbuffers/protobuf/blob/9b0fa3e7fbaf3463c3afa1c9ab111682108eeadb/src/google/protobuf/message_lite.h#L401

**Comment by fletcherdvalve** [comment]
> Last year Google added a deprecation warning for ByteSize:
OK, then let's just turn off that deprecation warning, then?  We have been warned, thank you!

@aiusepsi is that protobuf thing actually related to the crypto change?  I'm curious what's new; how did your change caused this to show up?

**Comment by tycho** [comment]
The deprecation is currently breaking Fedora Rawhide builds:

https://travis-ci.org/ValveSoftware/GameNetworkingSockets/jobs/634039162

I think the fix is reasonable enough. I cherry-picked it and cleaned up the commit message.

**Comment by tycho** [comment]
Confirmed, that change fixed the Fedora Rawhide builds: https://travis-ci.org/ValveSoftware/GameNetworkingSockets/builds/634049887

**Comment by tycho** [comment]
I added the `USE_CRYPTO/USE_CRYPTO25519` options for CMake in b445a0d02dc678f4f1e8e3823a529f5457145870 and `use_crypto/use_crypto25519` options for meson in ae735b094a56598f1292f85b6930b9f0abc03687, which you could easily extend to add libsodium support. Please rebase your changes with that in mind, and we'll look at merging them.

**Comment by tycho** [comment]
Nevermind, I got it integrated. I edited and merged the libsodium support, and credited @aiusepsi with authorship of the change. There were a few things I modified though, check the commit message on  b2ae48a2603909862d472ae484a956b1ee7d740f for details.

**Pull request closed without merging**
